
[package]
name = "rblx_obfuscator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
queues = "1.0.2"
full_moon = "0.19.0"
rbx_binary = "0.7.4"
rbx_dom_weak = "2.7.0"
rbx_types = "1.8.0"
